apiVersion: apps/v1
kind: Deployment
metadata:
 name: docker-deployment
 labels:
   app: docker
spec:
 template:
  metadata:
   name: docker-pod
   labels:
    app: docker
  spec:
    containers:
     - name: docker
       image: lekha7395/images:cmdb-3-Tier

#Mention the number of pods it has to create
 replicas: 1
 selector:
  matchLabels:
    app: docker
