apiVersion: apps/v1
kind: Deployment
metadata:
 name: nexus-deployment
 labels:
   app: nexus
spec:
 template:
  metadata:
   name: nexus-pod
   labels:
    app: nexus
  spec:
    containers:
     - name: nexus
       image: sonatype/nexus3
#Mention the number of pods it has to create
 replicas: 1
 selector:
  matchLabels:
    app: nexus

