apiVersion: apps/v1
kind: Deployment
metadata:
 name: tomcat-deployment
 labels:
   app: tomcat
spec:
 template:
  metadata:
   name: tomcat-pod
   labels:
    app: tomcat
  spec:
    containers:
     - name: tomcat
       image: tomcat
#Mention the number of pods it has to create
 replicas: 1
 selector:
  matchLabels:
    app: tomcat

